version: 2.1

executors:
  node-10:
    docker:
      - image: 'circleci/node:10-stretch'

jobs:
  test:
    executor: node-10
    steps:
      - run: yarn versions
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ checksum "yarn.lock" }}
            - node-v1-
      - run: yarn install --frozen-lockfile
      - run: yarn run prepack
      - run: yarn run test
      - save_cache:
          key: node-v1-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

workflows:
  test:
    jobs:
      - test
