version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - run: mkdir -p ~/.ssh
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: git config --global user.name $GIT_USER_NAME
      - run: git config --global user.email $GIT_USER_EMAIL
      - run: ssh-add -D
      - add_ssh_keys:
          fingerprints:
            - "SO:ME:FIN:G:ER:PR:IN:T"
      - run: npx @itinerisltd/composify

workflows:
    version: 2
    onSchedule:
      triggers:
        - schedule:
            cron: "0 * * * *"
            filters:
              branches:
                only: circleci
      jobs:
        - build:
            filters:
              branches:
                only: circleci
    onPush:
      jobs:
        - build:
            filters:
              branches:
                only: circleci
